# Generated by Django 3.2 on 2022-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220318_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseshedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
